services:
  web_ui:
    build:
      context: ./services/web_ui
    ports:
      - "8000:8000"
    env_file:
      - ./services/web_ui/.env
    volumes:
      - ./services/web_ui:/app
    command: python manage.py runserver 0.0.0.0:8000

  news_analyzer:
    build:
      context: ./services/news_analyzer
    ports:
      - "8001:80"
    env_file:
      - ./services/news_analyzer/.env
    volumes:
      - ./services/news_analyzer:/app
    command: uvicorn main:app --host 0.0.0.0 --port 80

  news_crawler:
    build:
      context: ./services/news_crawler
    env_file:
      - ./services/news_crawler/.env
    volumes:
      - ./services/news_crawler:/app
    command: python main.py