# Generated by Django 5.2.1 on 2025-06-15 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_alter_articles_category_alter_articles_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Articles'},
        ),
    ]
