# Generated by Django 5.2.1 on 2025-08-06 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0007_region_articles_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MainApp.region'),
        ),
    ]
