# Generated by Django 5.2.1 on 2025-08-06 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0008_region_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={},
        ),
    ]
